### ISSUE TITLE
Please provide a tag

### ISSUE THREAD

**Issue by smuzaffar** [xrootd/xrdcl-record#1]
We are trying to build this for CMS offline software, can you please please create a tag for the working code?
Thanks

**Comment by simonmichal** [comment]
@smuzaffar : absolutely, in the meanwhile I have pre-build RPMs: https://xrootd.web.cern.ch/xrootd/xrdcl-record/cc-7-x86_64/

**Comment by simonmichal** [comment]
@smuzaffar : I added two tags `v4.12.8` and `v5.4.2` (sorry for the delay, I forgot to push the stable branches when I was generating the RPMs and had to recreate it from scratch)

**Comment by smuzaffar** [comment]
thanks a lot @simonmichal
